DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  WALLET_ID VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS TB_WALLET;

CREATE TABLE TB_WALLET (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  BALANCE DECIMAL(18, 2) NOT NULL
);

DROP TABLE IF EXISTS TB_COMPANY;

CREATE TABLE TB_COMPANY (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  PRICE DECIMAL(18, 2) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS TB_ORDER;

CREATE TABLE TB_ORDER (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  ORDER_DATE DATE NOT NULL,
  ORDER_TYPE VARCHAR(255) NOT NULL,
  COMPANY_ID VARCHAR(255) NOT NULL,
  WALLET_ID VARCHAR(255) NOT NULL,
  AMOUNT INT NOT NULL,
  UNIT_PRICE DECIMAL(18, 2) NOT NULL,
  TOTAL_ORICE DECIMAL(18, 2) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS TB_WALLET_STOCK;

CREATE TABLE TB_WALLET_STOCK (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  COMPANY_CODE VARCHAR(255) NOT NULL ,
  WALLET_ID VARCHAR(255) NOT NULL,
  AMOUNT INT NOT NULL,
  BALANCE DECIMAL(18, 2) NOT NULL
)