DROP TABLE IF EXISTS TB_USER;
DROP TABLE IF EXISTS TB_ORDER;
DROP TABLE IF EXISTS TB_WALLET_STOCK;
DROP TABLE IF EXISTS TB_WALLET;
DROP TABLE IF EXISTS TB_COMPANY;

CREATE TABLE TB_COMPANY (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  PRICE DECIMAL(18, 2) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);

INSERT INTO TB_COMPANY (ID,NAME,CODE,PRICE,STATUS) VALUES ('inter-id', 'Inter', 'BIDI11', '66.51', 'ACTIVE');
INSERT INTO TB_COMPANY (ID,NAME,CODE,PRICE,STATUS) VALUES ('magalu-id', 'Magazine Luiza', 'MGLU3', '18.80', 'ACTIVE');
INSERT INTO TB_COMPANY (ID,NAME,CODE,PRICE,STATUS) VALUES ('sulamerica-id', 'Sulamérica', 'SULA11', '28.26', 'ACTIVE');
INSERT INTO TB_COMPANY (ID,NAME,CODE,PRICE,STATUS) VALUES ('engie-id', 'Engie', 'EGIE3', '38.30', 'ACTIVE');
INSERT INTO TB_COMPANY (ID,NAME,CODE,PRICE,STATUS) VALUES ('cvc-id', 'CVC', 'CVCB3', '20.87', 'ACTIVE');
INSERT INTO TB_COMPANY (ID,NAME,CODE,PRICE,STATUS) VALUES ('renner-id', 'Renner', 'LREN3', '36.95', 'ACTIVE');
INSERT INTO TB_COMPANY (ID,NAME,CODE,PRICE,STATUS) VALUES ('marisa-id', 'Marisa', 'AMAR3', '6.30', 'ACTIVE');

CREATE TABLE TB_USER (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  WALLET_ID VARCHAR(255) NOT NULL
);

CREATE TABLE TB_WALLET (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  BALANCE DECIMAL(18, 2) NOT NULL
);

CREATE TABLE TB_ORDER (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  ORDER_DATE DATE NOT NULL,
  ORDER_TYPE VARCHAR(255) NOT NULL,
  COMPANY_ID VARCHAR(255) NOT NULL,
  WALLET_ID VARCHAR(255) NOT NULL,
  AMOUNT INT NOT NULL,
  UNIT_PRICE DECIMAL(18, 2) NOT NULL,
  TOTAL_PRICE DECIMAL(18, 2) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);

CREATE TABLE TB_WALLET_STOCK (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  COMPANY_CODE VARCHAR(255) NOT NULL ,
  WALLET_ID VARCHAR(255) NOT NULL,
  AMOUNT INT NOT NULL,
  BALANCE DECIMAL(18, 2) NOT NULL
)