DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  WALLET_ID VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS WALLET;

CREATE TABLE WALLET (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  BALANCE DECIMAL(18, 2) NOT NULL
);

DROP TABLE IF EXISTS COMPANY;

CREATE TABLE COMPANY (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  PRICE DECIMAL(18, 2) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS B_ORDER;

CREATE TABLE B_ORDER (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  ORDER_DATE DATE NOT NULL,
  ORDER_TYPE VARCHAR(255) NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  AMOUNT INT NOT NULL
);